services:
  db:
    image: mysql:latest
    container_name: mysql-academy
    env_file: ./app-web/.env.development
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app-web/db/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"

volumes:
  mysql_data:
